name: Tests
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.23
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: WriteGoList
        run: go list -json -m all > go.list
      - name: nancy
        uses: sonatype-nexus-community/nancy-github-action@main
      - name: Run Keycloak
        run: |
          make start-keycloak
          sleep 15
      - name: Unit Tests
        run: |
          go test -v -failfast -race -cover -coverprofile=coverage.txt -covermode=atomic -p 100 -cpu 1,2 . > test.log
          cat test.log
      - name: Failed Logs
        if: failure()
        run: |
          cat test.log
          docker ps
          docker logs keycloak
      - name: CodeCov
        uses: codecov/codecov-action@v4.5.0
        with:
          file: ./coverage.txt
      # - name: Run golangci-lint
      #   uses: golangci/golangci-lint-action@v6.1.0
